apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor1
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: calendar-3a8aca06-cb13-4bad-822b-a6c774c80cb7
      eventName: calendar-3a8aca06-cb13-4bad-822b-a6c774c80cb7
      eventSourceName: sensor1-nw
    - name: github-a6eb42c9-3fa1-46fb-8ce2-4130dc28e77a
      eventName: github-a6eb42c9-3fa1-46fb-8ce2-4130dc28e77a
      eventSourceName: sensor1
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - create
            type: string
          - path: body.refType
            value:
              - branch
            type: string
  triggers:
    - template:
        name: trigger1
        conditions: >-
          calendar-3a8aca06-cb13-4bad-822b-a6c774c80cb7 ||
          github-a6eb42c9-3fa1-46fb-8ce2-4130dc28e77a
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: sensor1-trigger1-
              spec:
                arguments:
                  parameters:
                    - name: message
                      value: hello world
                workflowTemplateRef:
                  name: workflow-template-submittable
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-a6eb42c9-3fa1-46fb-8ce2-4130dc28e77a
                dataTemplate: branch created!! {{ .Input.body.repository.name }}
