apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sensor1
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-a6eb42c9-3fa1-46fb-8ce2-4130dc28e77a:
      events:
        - create
      repositories:
        - owner: vasil-cf
          names:
            - committers-test2
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/vasil-local-helm-runtime/sensor1/github-a6eb42c9-3fa1-46fb-8ce2-4130dc28e77a
        url: https://vasil-local.rnd-sandbox.cf-infra.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
